apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-app
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
      - name: posts-app
        image: {{ .Values.myapp.image.repository }}
        ports:
        - containerPort: {{ .Values.myapp.port }}
        env:
        - name: MONGODB_URI
          value: {{ .Values.myapp.environment.MONGODB_URI }}
      imagePullSecrets:
        - name: dockerhub-secret
