apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: posts-app
      annotations:
        redeploy-hash: "{{ .Values.redeploy-hash }}"
    spec:
      containers:
      - name: posts-app
        image: "{{ .Values.myapp.image.repository }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.myapp.port }}
        env:
        - name: MONGODB_URI
          value: "{{ .Values.myapp.environment.MONGODB_URI }}"
