apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
      - name: posts-app
        image: noabl/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.myapp.port }}
        env:
        - name: MONGODB_URI
          value: {{ .Values.myapp.environment.MONGODB_URI }}
