##for autocaling - horizontal pod autoscaler
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: postsApp
  namespace: default
  labels:
    app: postsApp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postsApp
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    {{- end }}
