apiVersion: v1
kind: Service
metadata:
  name: posts-app
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "30113"
    prometheus.io/path: "/metrics"
  labels:
    app: posts-app
spec:
  type: NodePort 
  selector: 
    app: posts-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000