apiVersion: v1
kind: Service
metadata:
  name: posts-app
  namespace: default

  labels:
    app: posts-app
spec:
  type: NodePort 
  selector: 
    app: posts-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000