FROM python:alpine

WORKDIR /app

# Install dependencies
RUN apk update && \
    apk add --no-cache curl tar

# Download and install mongosh
RUN curl -O https://downloads.mongodb.com/compass/mongosh-1.5.1-linux-x64.tgz && \
    tar -xzf mongosh-1.5.1-linux-x64.tgz && \
    ls -l mongosh-1.5.1-linux-x64 && \
    mv mongosh-1.5.1-linux-x64/bin/mongosh /usr/local/bin/ && \
    rm -rf mongosh-1.5.1-linux-x64.tgz mongosh-1.5.1-linux-x64

# Copy application requirements
COPY ./requirements.txt ./

# Upgrade pip and install Python dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 5000

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the application
CMD ["flask", "run"]
