apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: posts-app-monitor
  namespace: monitoring
  labels:
    app: posts-app
spec:
  selector:
    matchLabels:
      app: posts-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "80"
      path: /metrics
      interval: 15s
