# myapp values
myapp:
  image: 
    repository: noabl/flask-app:latest
  environment:
    MONGODB_URI: mongodb://myUserAdmin:changeme@mongo:27017/?authSource=admin
  port: 5000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
redeployhash: "1"