apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posts-app
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/noabl'
    targetRevision: 0.1.3
    chart: posts-app-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
