apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postsApp
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: docker.io/noabl/posts-app-repo
    targetRevision: 0.1.2
    chart: posts-app-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true